config/routes.rb
Rails.application.routes.draw do

  
  get '/' => 'homes#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
  }

  resources :posts

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
  end

  root 'posts#index'

  # フォローしたり、フォローを外すためのアクションを定義する準備
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # 「フォロー一覧」と「フォロワー一覧」のページ
  resources :users, only: [:show] do
    get :following, :follower, on: :member
  end

  # コメント
  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]

    # 通知一覧画面
    resources :notifications, only: :index
  end
end

app/models/notification.rb
class Notification < ApplicationRecord


	default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	def index
		@notifications.where(checked: false).each do |notification|
		  notification.update_attributes(checked: true)
		end
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def unchecked_notifications
		@notifications = current_user.passive_notifications.where(checked: false)
	end
end

app/views/notifications/_notification.html.slim
- visitor = notification.visitor
- visited = notification.visited
.col-md-6.mx-auto
  .form-inline
    span
      = link_to user_path(visitor) do
        = image_tag avatar_url(visitor).to_s, class: "icon_mini"
        strong
          = visitor.name
      = 'さんが'

      - case notification.action
      - when 'follow' then
        = "あなたをフォローしました"
      - when 'like' then
        = link_to 'あなたの投稿', notification.post, style: "font-weight: bold;"
        = "にいいねしました"
      - when 'comment' then
        - if notification.post.user_id == visited.id
          = link_to "あなたの投稿", notification.post, style: "font-weight: bold;"
        - else
          span
            = link_to post_path(notification.post) do
              = image_tag avatar_url(notification.post.user).to_s, class: "icon_mini" 
              strong
                = notification.post.user.name + 'さんの投稿'
        = "にコメントしました"
        p.text-muted.mb-0
          = Comment.find_by(id: notification.comment_id)&.comment

  .small.text-muted.text-right
    = time_ago_in_words(notification.created_at).upcase
  hr

app/views/notifications/index.html.slim
/ 自分の投稿に対するいいね、コメントは通知に表示しない
- notifications = @notifications.where.not(visitor_id: current_user.id)
- if notifications.exists?
  = render notifications
  = paginate notifications
- else
  p
    | 通知はありません