config/routes.rb
Rails.application.routes.draw do

  
  get '/' => 'homes#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
  }

  resources :posts

  resources :users, only: [:index, :show]
  resources :posts, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
  end

  root 'posts#index'

  # フォローしたり、フォローを外すためのアクションを定義する準備
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # 「フォロー一覧」と「フォロワー一覧」のページ
  resources :users, only: [:show] do
    get :following, :follower, on: :member
  end

  # コメント
  resources :posts, except: [:index] do
    resources :comments, only: [:create, :destroy]

    # 通知一覧画面
    resources :notifications, only: :index
  end
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader

	belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user

	# コメント
	has_many :comments, dependent: :destroy

	#  紐付け（ユーザと投稿）
	belongs_to:user

	# 投稿と通知モデルの紐付け
	has_many :notifications, dependent: :destroy

    def user
        return User.find_by(id: self.user_id)
    end

	# いいね通知の作成メソッド
	def create_notification_like!(current_user)
		# すでに「いいね」されているか検索
		temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
		# いいねされていない場合のみ、通知レコードを作成
		if temp.blank?
		  notification = current_user.active_notifications.new(
			post_id: id,
			visited_id: user_id,
			action: 'like'
		  )
		  # 自分の投稿に対するいいねの場合は、通知済みとする
		  if notification.visitor_id == notification.visited_id
			notification.checked = true
		  end
		  notification.save if notification.valid?
		end
	end


	# コメント通知の作成メソッド
	def create_notification_comment!(current_user, comment_id)
		# 自分以外にコメントしている人をすべて取得し、全員に通知を送る
		temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
		temp_ids.each do |temp_id|
		  save_notification_comment!(current_user, comment_id, temp_id['user_id'])
		end
		# まだ誰もコメントしていない場合は、投稿者に通知を送る
		save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
	end
	
	  def save_notification_comment!(current_user, comment_id, visited_id)
		# コメントは複数回することが考えられるため、１つの投稿に複数回通知する
		notification = current_user.active_notifications.new(
		  post_id: id,
		  comment_id: comment_id,
		  visited_id: visited_id,
		  action: 'comment'
		)
		# 自分の投稿に対するコメントの場合は、通知済みとする
		if notification.visitor_id == notification.visited_id
		  notification.checked = true
		end
		notification.save if notification.valid?
	  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @like = Like.new
    @user = User.find_by(id: @post.user_id) #ユーザーのデータを取得する処理
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.
      merge(text: params[:text],user_id: current_user.id)
    )

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:text, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <!-- ここから追加するコード -->
<div class="field3">
  <%= form.file_field :image %>
</div>

  <div class="field3">
    <%= form.text_field :text %>
  </div>

  <div class="field3_1">
    <%= form.submit "シェア" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編集ページ</h1>

<%= render 'form', post: @post %>

<%= link_to '詳細', @post %> |
<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>投稿一覧</h1>

<table>
  <thead>
    <tr>
      <th>投稿</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  


  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.text %></td>
        <td><%= link_to '詳細', post %></td>
        <td><%= link_to '編集', edit_post_path(post) %></td>
        <td><%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規投稿', new_post_path %>
<%= link_to "ユーザー一覧へ", users_path %>

app/views/posts/new.html.erb
<div class="conteiner">

    <div class="posts_field">
    <div class="field3">
        <h1>新規投稿</h1>
    </div>

    <%= render 'form', post: @post %>

    <%= link_to '戻る', posts_path %>
	</div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="conteiner">
<!-- 追加するコード-->
<% if @post.image? %>  <!-- アップロード画像がある場合に実行する -->
  <p>
    <%= image_tag @post.image.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
  </p>
<% end %>
<!-- ここまで -->

<p>
  <%= @post.text %>
</p>
  <div class="like_1">
    <h3>いいね件数: <%= @post.likes.count %></h3>
      <% if current_user.already_liked?(@post) %>
        <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
      <% else %>
        <%= button_to 'いいね', post_likes_path(@post) %>
      <% end %>
    <h2>いいねしたユーザー</h2>
        <% @post.liked_users.each do |user| %>
    <li><%= user.email %></li>
      <% end %>


<%
=begin%>
コメント
<%
=end%>
  <%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :comment, size: "40x5" %>
  <%= f.submit '送信', class: "btn-sm btn-primary" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>コメント投稿者</th>
      <th>コメント内容</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.name %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to "削除", post_comment_path(@post, comment), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%
=begin%>
 ここまで
<%
=end%>



    <%= link_to '編集', edit_post_path(@post) %> |
    <%= link_to '戻る', posts_path %>
  </div>
</div>